#!/bin/bash
#<pre><b>
# Script     : fullrunsuite
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 17-May-2004
# Purpose    : Production script to run "runsuite" and save the standard and
#              error output.
# SubScripts : makerun runsuite
# Notes      : You must run this in the programs directory where "runsuite" is.
#              Standard output will be written to "runsuite.log" and
#              standard error will be written to "runsuite.err"
# Usage      : fullrunsuite  
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
# N/A  Do not supply any parameters
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# 
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# No parameters allowed
if [ $# -gt 0 ] ; then
  echo "Error: (fullrunsuite) Do not supply any parameters" 1>&2
  exit 2
fi

makerun


./runsuite 1>runsuite.log 2>runsuite.err

