#!/bin/bash
#<pre><b>
# Script     : intnop
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 17-May-2004
# Purpose    : Production script to list programs in the titles file with no
#              corresponding sas program in the current directory.
# SubScripts : intitlesds nofile
# Notes      : Must be run in the programs directory. "intnop" is short for
#              "in titles no programs".
# Usage      : intnop  
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
# N/A  Do not supply any parameters
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# 
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# No parameters allowed
if [ $# -gt 0 ] ; then
  echo "Error: (intnop) Do not supply any parameters" 1>&2
  exit 1
fi

# Get a list of titles dataset programs, add the .sas extension
# and then call "nofile" to list those that do not exist to standard error.
intitlesds | awk '{print $0 ".sas"}' | nofile
