#!/bin/bash
#<pre><b>
# Script     : lisremap_win
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 20-Jul-2007
# Purpose    : Production script to list all the outputs file names that have
#              been remapped in a .titles "lisfile:" line (uses SAS).
# SubScripts : none
# SubMacros  : %allocr
# Notes      : WINDOWS VERSION
#              Output will be in program, label order
# Usage      : lisremap_win
#
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
# N/A  Do not supply any parameters
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# 
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# No parameters required
if [ $# -gt 0 ] ; then
  echo "Error: (lisremap_win) Do not supply any parameters" 1>&2
  exit 2
fi


# Write SAS code to a temporary file
cat > $HOME/lisremap_$$.sas << -----FINISH-----
%allocr
options validvarname=v7 nofmterr noovp nodate nonumber;
filename _outfile "$HOMEW\lisremap_$$.tmp";
data _titles;
  length lisfile $ 38;
  set &_ptlibref_..titles(where=(type='T' and number=1));
  if lisfile ne " ";
run;
proc sort data=_titles;
   by program label;
run;
data _null_;
  length templis $ 38;
  file _outfile notitles noprint;
  set _titles;
  if _n_=1 then do;
    put " ";
    put @1 "The following outputs have been mapped to different";
    put @1 'output file names using "lisfile:" .titles entries.';
    put @1 "===================================================";
  end;
  templis=trim(program)||".lis"||left(label);
  put @1 templis " ----> " lisfile;
run;
-----FINISH-----

# run the code
sas -nosplash -nologo -icon -log "$HOMEW" -sysin "$HOMEW\lisremap_$$.sas"

# if output file exists then cat it and delete it
if [ -f $HOME/lisremap_$$.tmp ] ; then
  cat $HOME/lisremap_$$.tmp 
  rm -f $HOME/lisremap_$$.tmp 
fi

# tidy up
rm -f $HOME/lisremap_$$.sas $HOME/lisremap_$$.log
