#!/bin/bash
#<pre><b>
# Script     : misscnt
# Version    : 2.0
# Author     : Roland Rashleigh-Berry
# Date       : 20-Feb-2007
# Purpose    : Display a count of variables and their number of missing 
#              observations (uses SAS)
# SubScripts : misscnt_win
# Notes      : Uses some of the sasautos extensions macros.
# Usage      : misscnt ds1 ds2
#              misscnt
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
#  1   (optional) Dataset or list of dataset for analysis. Defaults to the 
#      whole library.
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# rrb  11Feb07         Call misscnt_win for Windows configurations
# rrb  20Feb07         Remove call to allocation macro
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# if a Windows config then call misscnt_win and exit on return
if [ -n "$CYGWIN" ] ; then
  misscnt_win "$@"
  exit $?
fi

if [ $# -eq 0 ] ; then

############ no parameters specified so do for whole library ############

sas -stdio -sasuser work 2>/dev/null << -----FINISH-----
options validvarname=any nofmterr noovp nodate nonumber;
libname here './' access=readonly;
%dslist(here)

%macro doit;
  %do i=1 %to %words(&_dslist_);
    %let memname=%scan(&_dslist_,&i,%str( ));
    %misscnt(here.&memname)
  
    %if %length(&_miss_) %then %do;
      data miss;
        length memname $ 10 varname $ 20;
        retain memname "&memname";
        %do j=1 %to %words(%str(&_miss_));
          varname="%scan(%str(&_miss_),&j,%str( ))";
          output;
        %end;
      run;

      proc append base=base data=miss;
      run;
    %end;
  %end;

  data _null_;
    file stdout;
    set base;
    put @1 memname @12 varname;
  run;
%mend doit;

%doit
-----FINISH-----


else


for dataset in "$@" ; do

########## do for individual specified datasets ##########
sas -stdio -sasuser work 2>/dev/null << -----FINISH-----
options validvarname=any nofmterr noovp nodate nonumber;
libname here './' access=readonly;

%macro doit;
  %misscnt(here.$dataset)
  
  %if %length(&_miss_) %then %do;
    data miss;
      length memname $ 10 varname $ 20;
      retain memname "&memname";
      %do j=1 %to %words(%str(&_miss_));
        varname="%scan(%str(&_miss_),&j,%str( ))";
        output;
      %end;
    run;
  %end;
%mend doit;

%doit

data _null_;
  file stdout;
  set miss;
  put @1 "%upcase($dataset)" @12 varname;
run;
-----FINISH-----

done


fi
