#!/bin/sh
#<pre><b>
# Script     : showfmts
# Version    : 2.0
# Author     : Roland Rashleigh-Berry
# Date       : 20-Feb-2007
# Purpose    : To display a list of all stored formats that would be available
#              if a call to %allocr were made from the current directory 
#              (uses SAS).
# SubScripts : showfmts_win
# SubMacros  : %allocr
# Notes      : 
# Usage      : showfmts
#
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
# N/A  Do not supply any parameters
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# rrb  24Nov05         -stdio
# rrb  11Feb07         Call showfmts_win for Windows configurations
# rrb  20Feb07         Call %allocr macro
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# if a Windows config then call showfmts_win and exit on return
if [ -n "$CYGWIN" ] ; then
  showfmts_win
  exit $?
fi

# Feed SAS code into standard input
sas -stdio -sasuser work 2>/dev/null << -----FINISH-----
%allocr

%macro showfmts;
  %local i fmtpath cat;
  %let fmtpath=%fmtpath;
  %do i=1 %to %words(&fmtpath);
    %let cat=%scan(&fmtpath,&i,%str( ));
    %if %sysfunc(cexist(&cat)) %then %do;
      proc format lib=%scan(&cat,1,%str(,)) cntlout=out(keep=fmtname type);
      proc append data=out base=allout;
      run;
    %end;
  %end;

  data showfmts;
    length name $ 8;
    set allout;
    if type in ('C','P','N');
    if type='C' then name='$'||fmtname;
    else name=fmtname;
  run;

  proc sort nodupkey data=showfmts;
    by name;
  run;

  data _null_;
    file stdout;
    set showfmts;
    put @1 name;
  run;

%mend;
%showfmts;

-----FINISH-----
