#!/bin/bash
#<pre><b>
# Script     : slinks
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 13-Dec-2004
# Purpose    : To list all symbolic links in the current directory and downwards
# SubScripts : none
# Notes      : Uses the "find" command. Error output (typically for directories
#              with read protection) is suppressed.
# Usage      : slinks 
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
# N/A  Do not use parameters   
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# 
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# No parameters required
if [ $# -gt 0 ] ; then
  echo "Usage: slinks (do not supply any parameters)" 1>&2
  exit 1
fi

find . -type l -ls  2>/dev/null
