#!/bin/bash
#<pre><b>
# Script     : suffix
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 23-Jun-2004
# Purpose    : To suffix a list of items with a given string
# SubScripts : none
# Notes      : You must pipe into this utility
# Usage      : xxxxx | suffix '.sas'
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
#  1   string to suffix each item with
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# 
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# One string parameter allowed
if [ $# -ne 1 ] ; then
  echo "Usage: xxxx | suffix 'string'" 1>&2
  exit 1
fi

gawk '{print $0 string}' string="$1"
