#!/bin/bash
#<pre><b>
# Script     : badprognames
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 07-Jun-2005
# Purpose    : To list which SAS programs do not have a correct program name
#              in the standard header.
# SubScripts : none
# Notes      : none
# Usage      : badprognames 
#              
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
# N/A  Do not supply any parameters
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# 
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# No parameters required
if [ $# -gt 0 ] ; then
  echo "Usage: badprognames # do not supply any parameters" 1>&2
  exit 1
fi

grep "^/ Program      : .*" *.sas | gawk -F: 'index($3,$1)==0'
