#!/bin/bash
#<pre><b>
# Script     : digits2x
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 22-Nov-2005
# Purpose    : To change numeric values in a report to "x"s to make it
#              suitable for a table shell.
# SubScripts : none
# Notes      : This does not work perfectly but should make it easier to turn
#              an output listing into a table shell.
# Usage      : digits2x report.lis > template.txt
#              
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
#  1   input file
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# 
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

if [ $# -ne 1 ] ; then
  echo "Usage: digits2x report.lis > exes.txt" 1>&2
  exit 1
fi

sed -e 's%[0-9][0-9][A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9]%xxMTH20xx%g' \
-e 's%[0-9][0-9][A-Z][A-Z][A-Z][0-9][0-9]%xxMTHxx%g' \
-e 's%[0-9][0-9]/[0-9][0-9]/[0-9][0-9][0-9][0-9]%xx/xx/xxxx%g' \
-e 's%[0-9][0-9]/[0-9][0-9]/[0-9][0-9]%xx/xx/xx%g' \
-e 's%(N=[0-9][0-9][0-9][0-9])%(N=xxxx)%g' \
-e 's%(N=[0-9][0-9][0-9])%(N=xxx)%g' \
-e 's%(N=[0-9][0-9])%(N=xx)%g' \
-e 's%(N=[0-9])%(N=x)%g' \
-e 's%  ..[0-9][0-9] (..[0-9]\.[0-9]) [0-9].. %   xxx ( xx.x) xxx %g' \
-e 's% [0-9][0-9]/[0-9][0-9] ( .[0-9]\.[0-9])% xx/xx ( xx.x)%g' \
-e 's% [0-9]/[0-9][0-9] ( .[0-9]\.[0-9])% x/xx ( xx.x)%g' \
-e 's%  .[0-9][0-9] (..[0-9]\.[0-9])%  xxx ( xx.x)%g' \
-e 's%  .[0-9] (..[0-9]\.[0-9])%  xx ( xx.x)%g' \
-e 's% [0-9][0-9][0-9][0-9][0-9]\.[0-9] % xxxxx.x %g' \
-e 's% [0-9][0-9][0-9][0-9]\.[0-9][0-9] % xxxx.xx %g' \
-e 's%  [0-9][0-9][0-9][0-9]\.[0-9] %  xxxx.x %g' \
-e 's%  [0-9][0-9][0-9]\.[0-9][0-9] %  xxx.xx %g' \
-e 's%  [0-9][0-9][0-9]\.[0-9] %  xxx.x %g' \
-e 's%  [0-9][0-9]\.[0-9][0-9] %  xx.xx %g' \
-e 's%  [0-9]\.[0-9][0-9] %  x.xx %g' \
-e 's%  [0-9][0-9]\.[0-9] %  xx.x %g' \
-e 's%  [0-9]\.[0-9]  %  x.x  %g' \
-e 's%  [0-9][0-9][0-9][0-9][0-9] %  xxxxx %g' \
-e 's% [0-9][0-9][0-9][0-9][0-9]  % xxxxx  %g' \
-e 's%  [0-9][0-9][0-9][0-9] %  xxxx %g' \
-e 's%  [0-9][0-9][0-9] %  xxx %g' \
-e 's%  [0-9][0-9] %  xx %g' \
-e 's% [0-9][0-9][0-9]\.[0-9][0-9][0-9][0-9]% xxx.xxxx%g' \
-e 's% [0-9][0-9]\.[0-9][0-9][0-9][0-9]% xx.xxxx%g' \
-e 's% [0-9]\.[0-9][0-9][0-9][0-9]% x.xxxx%g' \
-e 's% [0-9][0-9][0-9]\.[0-9][0-9][0-9]% xxx.xxx%g' \
-e 's% [0-9][0-9]\.[0-9][0-9][0-9]% xx.xxx%g' \
-e 's% [0-9]\.[0-9][0-9][0-9]% x.xxx%g' \
-e 's% [0-9][0-9][0-9]\.[0-9][0-9]$% xxx.xx%g' \
-e 's% [0-9][0-9]\.[0-9][0-9]$% xx.xx%g' \
-e 's% [0-9]\.[0-9][0-9]$% x.xx%g' \
-e 's%  [0-9][0-9][0-9][0-9]\.[0-9]$%  xxxx.x%g' \
-e 's%  [0-9][0-9][0-9]\.[0-9]$%  xxx.x%g' \
-e 's%  [0-9][0-9]\.[0-9]$%  xx.x%g' \
-e 's%  [0-9]\.[0-9]$%  x.x%g' \
-e 's% [0-9][0-9][0-9][0-9][0-9]$% xxxxx%g' \
-e 's% [0-9][0-9][0-9][0-9]$% xxxx%g' \
-e 's% [0-9][0-9][0-9]$% xxx%g' \
-e 's%   [0-9][0-9]$%   xx%g' \
-e 's% 0\.[0-9][0-9]% x.xx%g' \
-e 's%-0\.[0-9][0-9][0-9]%-x.xxx%g' \
-e 's%(0\.[0-9][0-9][0-9]%(x.xxx%g' \
-e 's%   [0-9] %   x %g' $1
