#!/bin/bash
#<pre><b>
# Script     : nobs_win
# Version    : 1.0
# Author     : Roland Rashleigh-Berry
# Date       : 11-Feb-2007
# Purpose    : To display the number of observations a dataset has (uses SAS)
# SubScripts : none
# Notes      : WINDOWS VERSION
# Usage      : nobs_win       # acts on all datasets in current library
#              nobs_win p*    # acts on all datasets starting with "p"
#              nobs_win dem labs   # acts on two datasets
#              nobs_win dem        # acts on one dataset
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
#  1   (optional) dataset(s) to list observations for
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# rrb  11Feb07         Call nobs_win for Windows configurations
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# Write SAS code to a temporary file
cat > $HOME/nobs_$$.sas << -----FINISH-----
options validvarname=any nofmterr noovp nodate nonumber;
filename _outfile "$HOMEW\nobs_$$.tmp";
%let dsets=$@ ;
libname here './' access=readonly;
%macro temp;
data nobs(keep=memname nobs);
  set sashelp.vtable(where=(libname="HERE" and memtype="DATA"
     %if %length(&dsets) %then %do;
     and memname in (
     %let i=1;
     %do %while(%scan(&dsets,&i,%str( )) NE );
       "%upcase(%scan(%scan(&dsets,&i,%str( )),1,.))"
       %let i=%eval(&i+1);
     %end;
     )
     %end;
      ));
run;
%mend temp;
%temp;
data _null_;
  file _outfile notitles noprint;
  set nobs;
  put @1 memname @12 nobs;
run;
-----FINISH-----

# run the code
sas -nosplash -nologo -icon -log "$HOMEW" -sysin "$HOMEW\nobs_$$.sas"

# if output file exists then cat it and delete it
if [ -f $HOME/nobs_$$.tmp ] ; then
  cat $HOME/nobs_$$.tmp 
  rm -f $HOME/nobs_$$.tmp 
fi

# tidy up
rm -f $HOME/nobs_$$.sas $HOME/nobs_$$.log
