document.write ('<script language="JavaScript">\n');
document.write ('<!--\n');
document.write ('google_position = ');
document.write ("'");
document.write ('below');
document.write ("'");
document.write ('; \n');
document.write ('google_ad_client = ');
document.write ("'");
document.write ('ca-lycos_tripod');
document.write ("'");
document.write (';\n');
document.write ('google_ad_channel = ');
document.write ("'");
document.write ('TRI_below_728x90');
document.write ("'");
document.write (';\n');
document.write ('google_ad_width = 728;\n');
document.write ('google_ad_height = 90;\n');
document.write ('google_ad_format = ');
document.write ("'");
document.write ('728x90_pas_abgnc');
document.write ("'");
document.write (';\n');
document.write ('google_color_bg = ');
document.write ("'");
document.write ('ffffff');
document.write ("'");
document.write (';\n');
document.write ('google_color_border = ');
document.write ("'");
document.write ('ffffff');
document.write ("'");
document.write (';\n');
document.write ('google_ad_type = ');
document.write ("'");
document.write ('text');
document.write ("'");
document.write (';\n');
document.write ('google_alternate_ad_url = ');
document.write ("'");
document.write ('http://ad.yieldmanager.com/st?ad_type=iframe&amp;ad_size=728x90&amp;section=67698');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('google_skip = ');
document.write ("'");
document.write ('4');
document.write ("'");
document.write (';\n');
document.write ('google_safe = ');
document.write ("'");
document.write ('high');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('// -->\n');
document.write ('</script>\n');
document.write ('<script language="JavaScript" src=http://pagead2.googlesyndication.com/pagead/show_ads.js>\n');
document.write ('</script>\n');
document.write ('<noscript>\n');
document.write ('<img height=1 width=1 border=0 src=http://pagead2.googlesyndication.com/pagead/imp.gif?client=ca-lycos_tripod&channel=TRI_below_728x90&event=noscript>\n');
document.write ('</noscript>');
