/*******
  Credit Risk Scorecards: Development and Implementation using SAS
  (c)  Mamdouh Refaat
********/


/*******************************************************/
/* Macro SCCCode */
/*******************************************************/
%macro SCCCode(SCDS,BasePoints, BaseOdds, PDO, IntOpt,FileName);
/* writing the scorecard generated by the scorecard dataset to an output
  file FileName generating C code
  If The option IntOpt=1 then we convert the points to integer values
  otherwise they are left as numbers */

/* direct the output to the filename */
proc sort data=&SCDS;
by VarType VarName;
run;

data _null_;
set &SCDS nobs=nx;
by VarType VarName;
file "&FileName";
length cond $300.;
length value $300.;
if _N_ =1 then do;
	put '/*********************************************/' ;
	put '/*********************************************/';
	put '/***** Automatically Generated Scorecard *****/';
	put '/*********************************************/';
	put '/**************     C CODE      **************/';
	put;
	put '/* Scorecard Scale : */';
	put "/*  Odds of [ 1 : &BaseOdds ] at  [ &BasePoints ] Points ";
    put "     with PDO of [ &PDO ] */";
	put; 
	put '/*********************************************/';
	put '/*********************************************/';
	put ;

	put '/*********************************************/';
	put '/*********************************************/';
	put;
	put '/****  Modify this part to input the data variables needed for  scoring ***/';
	put '/****  The implementation can be run within a for loop                  ***/';
	put;
	put '/*********************************************/';
	put '/* for (customer=0; customer<Total; customer++) */';
	put '/* {                                            */';
end; 

/* print the dataset RulesDS */


%if &IntOpt=1 %then xPoints=int(Points);
%else xPoints=Points; ;

if VarName="_BasePoints_" then do;
	put '/*********************************************/';
	put "/* Base Points   */";
	put '/*********************************************/';
    put "points=" xPoints ";";
                            end;
 else do;
   if first.VarName then do;
	put '/*********************************************/';
	put "/* Variable : " VarName "    *****/";
	put '/*********************************************/';
                      end;
    value= ")  points=points +("||compress(xPoints)||");";

    /* The rule */
    if VarType=1 then  do;/* continuous */
	if first.VarName then  cond='if( '||compress(VarName)||' <= ('||compress(UL) || ')'; 
	else if last.VarName then cond='if( '||compress(VarName)||' > ('|| compress(LL)||') ';
    else cond='if( '||compress(VarName)||' > ('|| compress(LL)||') && '||compress(VarName)||' <= ('||compress(UL) || ')'; 
                       end; 
    else if VarType=2 then /* nominal string */
	cond = 'if ('||compress(VarName)|| '==' || "'"||(compress(Category))||"'" ; 

	else /* nominal numeric */
	cond='if(' ||compress(VarName)|| '==' || compress(N_Category); 
	
	put "      " cond value;

 end;

	 if _N_=Nx then do;
			put '/* } */'; 
			put '/*************End of the scoring  Loop *******/';
			put;
	 end;
run;


%mend;

