/*******
  Credit Risk Scorecards: Development and Implementation using SAS
  (c)  Mamdouh Refaat
********/



/*******************************************************/
/* Macro SCSASCode */
/*******************************************************/
%macro SCSasCode(SCDS,BasePoints, BaseOdds, PDO, IntOpt,FileName);
/* writing the scorecard generated by the scorecard dataset to an output
  file FileName generating SAS code
  If The option IntOpt=1 then we convert the points to integer values
  otherwise they are left as numbers */

/* direct the output to the filename */

proc sort data=&SCDS;
by VarType VarName;
run;

data _null_;
set &SCDS nobs=nx;
by VarType VarName;
file "&FileName";
length cond $300.;
length value $300.;

if _N_ =1 then do;
	put '/*********************************************/' ;
	put '/*********************************************/';
	put '/***** Automatically Generated Scorecard *****/';
	put '/*********************************************/';
	put '/************    SAS CODE             ********/';
	put;
	put '/* Scorecard Scale : */';
	put "/*  Odds of [ 1 : &BaseOdds ] at  [ &BasePoints ] Points ";
    put "     with PDO of [ &PDO ] */";
	put; 
	put '/*********************************************/';
	put '/*********************************************/';
	put ;


	put '/********** START OF SCORING DATA STEP *******/';
	put '/*********************************************/';
	put '/*********************************************/';
	put;
	put 'DATA SCORING;        /********** Modify ************/';
	put ' SET ScoringDataset; /********** Modify ************/';
	put;
	put '/*********************************************/';
	put '/*********************************************/';
end; 

/* print the dataset RulesDS */


%if &IntOpt=1 %then xPoints=int(Points);
%else xPoints=Points; ;

if VarName="_BasePoints_" then do;
	put '/*********************************************/';
	put "/* Base Points   */";
	put '/*********************************************/';
put "Points=" xPoints ";";
                            end;
 else do;
   if first.VarName then do;
	put '/*********************************************/';
	put "/* Variable : " VarName "    *****/";
	put '/*********************************************/';
                      end;
    value= "  THEN  Points=Points +("||compress(xPoints)||");";

    /* The rule */
    if VarType=1 then  do;/* continuous */
	if first.VarName then  cond='IF '||compress(VarName)||' LE ('||compress(UL) || ') '; 
	else if last.VarName then cond='IF '||compress(VarName)||' GT ('|| compress(LL)||')';
    else cond='IF '||compress(VarName)||' GT ('|| compress(LL)||') AND '||compress(VarName)||' LE ('||compress(UL) || ') '; 
                       end; 
    else if VarType=2 then /* nominal string */
	cond = 'IF '||compress(VarName)||' = '|| quote(compress(Category)) ; 

	else /* nominal numeric */
	cond='IF '||compress(VarName)||' = ('|| compress(N_Category)||') '; 
	
	put "      " cond value;

 end;

 if _N_=Nx then do;
	put 'RUN;'; 
	put;
	put '/*************END OF SCORING DATA STEP *******/';
	put '/*********************************************/';
	end;
run;


%mend;

