data testdata(keep=times subject);
	subject=1;
	do times =1 to 100;
		do clone=1 to times;
		output;
		end;
	end;
run;
proc freq data=testdata noprint;
	by times;
	tables subject / out=freq_out;
run;
data final;	
	set freq_out;
	format delta e32.8;
	if percent ^= 100.;
	delta=percent-110.;
	if delta=0.0 then true=1;
	else true=0;
	d=percent-100;
run;
