data ds1(keep=pat pt x1);
	do i=0 to 1 by 0.1;
		pat=10*(i+0.1);
		pt=round(pat,0.01);
		if pat=pt then x1=1;
		else x1=0;
		output;
	end;
run;
data ds2(keep= pat pt x2);
	set ds1(keep=pt);
	pat=_n_;
	if pat=pt then x2=1;
	else x2=0;
run;
data check;
	merge ds1 ds2(drop=pt);
	by pat;
run;
