#!/bin/bash
#<pre><b>
# Script     : intitlabels_win
# Version    : 1.1
# Author     : Roland Rashleigh-Berry
# Date       : 02-Mar-2007
# Purpose    : Production script to list all the programs in the titles dataset
#              with output labels (uses SAS).
# SubScripts : none
# SubMacros  : %allocr
# Notes      : WINDOWS VERSION
#              There will be no .sas extension. There is one line per label
#              in the form:
#              progname label
# Usage      : intitlabels_win
#
#===============================================================================
# PARAMETERS:
#-pos- -------------------------------description-------------------------------
# N/A  Do not supply any parameters
#===============================================================================
# AMENDMENT HISTORY:
# init --date-- mod-id ----------------------description------------------------
# rrb  20Feb07         Call %allocr macro
# rrb  02Mar07         Use "&_ptlibref_.." instead of "der."
#===============================================================================
# This is public domain software. No guarantee as to suitability or accuracy is
# given or implied. User uses this code entirely at their own risk.
#===============================================================================

# No parameters required
if [ $# -gt 0 ] ; then
  echo "Error: (intitlabels) Do not supply any parameters" 1>&2
  exit 2
fi

# Write SAS code to a temporary file
cat > $HOME/intitlabels_$$.sas << -----FINISH-----
%allocr
options validvarname=v7 nofmterr noovp nodate nonumber;
filename _outfile "$HOMEW\intitlabels_$$.tmp";
proc sort nodupkey data=&_ptlibref_..titles(where=(type='T' and number=1))
                    out=_titles(keep=program label);
  by program label;
run;
data _null_;
  file _outfile notitles noprint;
  set _titles;
  put @1 program label;
run;
-----FINISH-----

# run the code
sas -nosplash -nologo -icon -log "$HOMEW" -sysin "$HOMEW\intitlabels_$$.sas"

# if output file exists then cat it and delete it
if [ -f $HOME/intitlabels_$$.tmp ] ; then
  cat $HOME/intitlabels_$$.tmp 
  rm -f $HOME/intitlabels_$$.tmp 
fi

# tidy up
rm -f $HOME/intitlabels_$$.sas $HOME/intitlabels_$$.log
